unique_ids:
  assets:
    standard-page.html: V3NEFJNJ7S2PVD4RRDLYZMCCC7UNSNR3
    theme.css: UEIM4UWH6WIGLHICRE2MD2OVKH5IBLJQ
  forms:
    Form1: VFK6QYXD3HF3PBGFDF6U7P7RAI5F2U3S
  modules: {}
  scripts: {}
  server_modules: {}
